language: python
python: 3.6
services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install psycopg2 --quiet
  - pip install git+https://github.com/cameroncurry/nabla_core.git
  - pip install git+https://github.com/cameroncurry/questrade.git
before_script:
  - psql -c "create database travis_ci_test;" -U postgres
script:
  - python setup.py test